type Person = {
  id: string;
  nome: string;
  id_municipio?: string;
  id_comuna?: string;
  id_provincia?: string;
  n_identificacao?: string;
  id_tipo_identificacao?: string;
  genero: boolean;
  id_estado_civil?: string;
  nome_pai?: string;
  nome_mae?: string;
  naturalidade?: string;
  altura?: number;
  data_nascimento?: Date;
  data_emissao?: Date;
  data_validade?: Date;
  foto: string! | null;
  identificacao?: Identification;
  usuario: Omit<User, "permissoes_telas" | "pessoa"> | null;
  email?: Omit<Email,"pessoa">;
  telefone?: Phone;
  aluno: Student | null;
};
type PersonToUpdate = {
  telefone: Phone;
  nome?: string;
  id_municipio?: string;
  id_comuna?: string;
  id_provincia?: string;
  n_identificacao?: string;
  id_tipo_identificacao?: string;
  id_genero?: string;
  id_estado_civil?: string;
  nome_pai?: string;
  nome_mae?: string;
  naturalidade?: string;
  altura?: number;
  data_nascimento?: Date;
  data_emissao?: Date;
  data_validade?: Date;
};
